// File generated by `flutterfire configure`, do not edit manually.
// This file was generated for Android platform.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALISkSwbCQKwY2MwtqeYIOc38wKRC4wsA',
    appId: '1:273167992012:android:6757cb1fee2b7f8e852e69',
    messagingSenderId: '273167992012',
    projectId: 'la-nona-cafeteria',
    storageBucket: 'la-nona-cafeteria.firebasestorage.app',
  );
}
